In [1]:
import numpy as np

배열의기초

In [4]:
x2 = np.random.randint(10,size=(3,4))
print(x2)

[[3 9 1 3]
 [9 8 3 3]
 [2 5 7 3]]


In [6]:
print(x2.ndim)
print(x2.shape)
print(x2.size)
print(x2.dtype)

2
(3, 4)
12
int32


찾고 골라내기
-indexing: 인덱스로 값을 찾아냄
 [0 1 2 3 4 5 6]

In [11]:
x = np.arange(7)
print(x[3])
x[0] = 10
print(x[0])

3
10


찾고 잘라내기 - slicing: 인덱스 값으로 배열의 부분을 가져옴
[0 1 2 3 4 5 6]

In [12]:
print(x[1:4])
print(x[1:])
print(x[:4])
print(x[::2])

[1 2 3]
[1 2 3 4 5 6]
[10  1  2  3]
[10  2  4  6]


모양바꾸기 reshape:array의 shape 변경

In [15]:
x = np.arange(8)
print(x.shape)
print(x)
x2 = x.reshape((2,4))
print(x2)

(8,)
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


이어 붙이고 나누고이어 붙이고 나누고
concatenate:array를 이어붙임 
[0 1 2][3 4 5] [0 1 2 3 4 5]

In [17]:
x = np.array([0,1,2])
y = np.array([3,4,5])
z = np.concatenate([x,y])
print(z)

[0 1 2 3 4 5]


이어 붙이고 나누고 np.concatenate:axis 축을 기준으로 이어붙임

In [20]:
matrix = np.arange(4).reshape(2,2)
print(matrix)
new_mat_0 = np.concatenate([matrix, matrix], axis = 0)
print(new_mat_0)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [21]:
new_mat_1 = np.concatenate([matrix, matrix], axis=1)
print(new_mat_1)

[[0 1 0 1]
 [2 3 2 3]]


np.split: axis 축을 기준으로 분할

In [26]:
matrix= np.arange(16).reshape(4,4)
print(matrix)
upper, lower = np.split(matrix, [3], axis=0)
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [27]:
left, right = np.split(matrix, [3], axis=1)
print(left)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


루프는 느리다 
array의 모든 원소에 5를 더해서 만드는 함수

In [28]:
def add_five_to_array(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output
values = np.random.randint(1,10, size=5)
print(values)
print(add_five_to_array(values))

[3 6 9 2 4]
[ 8. 11. 14.  7.  9.]


만약 array가 크다면??

In [30]:
big_array = np.random.randint(1,100,size=10000000)

print(add_five_to_array(big_array))
#대략 6초걸림


[61. 15. 65. ... 95. 67. 86.]
[61 15 65 ... 95 67 86]


In [31]:
print(big_array+5) #바로나옴

[61 15 65 ... 95 67 86]


기본연산
array 는 +,-,*,/ 에 대한 기본 연산을 지원

In [32]:
x = np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*2)
print(x/2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]


행렬간 연산
다차원 행렬에서도 적용 가능

In [34]:
x = np.arange(4).reshape((2,2))
print(x)
y = np.random.randint(10,size=(2,2))
print(y)

print(x+y)
print(x-y)

#동일한 공간에 있는것 끼리

[[0 1]
 [2 3]]
[[6 9]
 [0 8]]
[[ 6 10]
 [ 2 11]]
[[-6 -8]
 [ 2 -5]]


브로드캐스팅 
Broadcasting:shape이 다른 array끼리 연산

In [35]:
x = np.arange(4).reshape((2,2))
print(x)
print()
print(x+5)

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


Broadcasting:shape 이 다른 array 끼리 연산

In [46]:
print(x)
print()
print(np.array([1,2]))
print()
print(x + np.array([1,2]))


[[0 1]
 [2 3]]

[1 2]

[[1 3]
 [3 5]]


In [54]:
a = np.arange(3)
print(a)
print(a.shape)
print()
b = np.arange(3).reshape(3,1)
print(b)
print(b.shape)
print()
print(b + a)

[0 1 2]
(3,)

[[0]
 [1]
 [2]]
(3, 1)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


집계함수
집계 : 데이터에 대한 요약 통계

In [57]:
x = np.arange(8).reshape((2,4))
print(x)

print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))

[[0 1 2 3]
 [4 5 6 7]]
28
0
7
3.5


In [59]:
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
#0(가로기준)은 세로로
#1(세로기준)은 가로로

[ 4  6  8 10]
[ 6 22]


마스킹연산:True, False array를 통해서 특정 값들을 뽑아내는 방법

In [64]:
x = np.arange(5)
print(x)
print(x<3)
print(x>5)
print(x[x<3]) #x의 요소 x가 3보다 작은값을 출력

[0 1 2 3 4]
[ True  True  True False False]
[False False False False False]
[0 1 2]
