In [3]:
import numpy as np

In [9]:
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

오 신기


In [17]:
np.random.random((2,2))

array([[0.36840254, 0.70322509],
       [0.9386454 , 0.29676965]])

In [20]:
np.random.normal(0,1,(2,2))

array([[-0.50919509,  0.13737381],
       [ 1.01937126, -0.72058212]])

In [24]:
np.random.randint(0,10, (3,2))

array([[1, 0],
       [5, 3],
       [6, 8]])

In [33]:
x2 = np.random.randint(10, size =(3,4))

In [34]:
print(x2)

[[7 7 2 8]
 [2 3 2 2]
 [8 6 1 4]]


In [35]:
x2.ndim

2

In [36]:
x2.shape

(3, 4)

In [37]:
x2.size

12

In [38]:
x2.dtype

dtype('int32')

In [4]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [5]:
x[1:4]

array([1, 2, 3])

In [6]:
x[2:]

array([2, 3, 4, 5])

In [7]:
x[:4]

array([0, 1, 2, 3])

In [8]:
x[::2]

array([0, 2, 4])

In [10]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
x.shape

(8,)

In [13]:
x2 = x.reshape((2,4))
x2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
x2.size

8

In [15]:
x2.shape

(2, 4)

- concatenate() : 이어붙이기

In [19]:
x = np.array([0,1,2])
y = np.array([3,4,5])
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5])

In [20]:
mat = np.arange(4)
mat

array([0, 1, 2, 3])

In [22]:
mat = np.arange(4).reshape(2,2)
mat

array([[0, 1],
       [2, 3]])

In [24]:
np.concatenate([mat,mat], axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [25]:
np.concatenate([mat,mat], axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [27]:
import tensorflow as tf

다음 주소에서 vc_redist.x64.exe를 다운로드 받아 설치하면 해결됩니다. 



https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads



In [28]:
mat1 = np.arange(4)
mat1

array([0, 1, 2, 3])

In [31]:
mat1 = np.arange(16).reshape(4,4)
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
upper, lower = np.split(mat1, [2], axis=0)

In [43]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
left, right = np.split(mat1, [2], axis=1)

In [37]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [38]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [45]:
def add_five_to_array(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] +5
    return output
    
values = np.random.randint(1, 10, size=5)
add_five_to_array(values)

array([ 7.,  6.,  7., 10.,  7.])

In [53]:
x = np.arange(4)
print(x)
x + 5

[0 1 2 3]


array([5, 6, 7, 8])

In [49]:
x-5

array([-5, -4, -3, -2])

In [50]:
x*5

array([ 0,  5, 10, 15])

In [51]:
x/5

array([0. , 0.2, 0.4, 0.6])

In [54]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [56]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [58]:
y = np.random.randint(10, size=(2,2))
y

array([[8, 8],
       [4, 2]])

In [59]:
x+y

array([[8, 9],
       [6, 5]])

In [60]:
x-y

array([[-8, -7],
       [-2,  1]])

In [67]:
np.arange(3).shape

(3,)

In [68]:
np.arange(3)

array([0, 1, 2])

In [66]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [70]:
np.arange(3).reshape(3,1).shape

(3, 1)

In [64]:
np.arange(3).reshape(3,1) + np.arange(3)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [71]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
x = np.arange(8).reshape(2,4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
np.sum(x)

28

In [75]:
np.min(x)

0

In [76]:
np.max(x)

7

In [77]:
np.mean(x)

3.5

In [78]:
np.sum(x, axis=0)

array([ 4,  6,  8, 10])

In [79]:
np.sum(x, axis=1)

array([ 6, 22])

In [80]:
x = np.arange(8).reshape((2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [82]:
x < 3

array([ True,  True,  True, False, False, False, False, False])

In [83]:
x[x<3]

array([0, 1, 2])

In [84]:
import pandas as pd

data = pd.Series([1,2,3,4])
print(data)

0    1
1    2
2    3
3    4
dtype: int64


In [86]:
data = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data)

a    1
b    2
c    3
d    4
dtype: int64


In [88]:
data['b']
#문자를 입력할때는 문자열로 입력해야함


2

In [89]:
data.b

2

In [91]:
data2 = pd.Series([1,2,3,4,5], index=['수','우','미','양','가'])
print(data2)

수    1
우    2
미    3
양    4
가    5
dtype: int64


In [96]:
data2.우

2

In [97]:
data3 = pd.Series([1,2,3,4,5], index=['수','우','미','양','가'],
                name = "영우 성적표")
data3

수    1
우    2
미    3
양    4
가    5
Name: 영우 성적표, dtype: int64

In [104]:
population_dict = {
'korea': 5180,
'japan': 12718,
'china': 141500,
'usa': 32676
}
population = pd.Series(population_dict, name = "세계인구")
print(population)

korea      5180
japan     12718
china    141500
usa       32676
Name: 세계인구, dtype: int64


In [119]:
population_dict

{'korea': 5180, 'japan': 12718, 'china': 141500, 'usa': 32676}

In [107]:
gdp_dict = {
'korea': 169320000,
'japan': 516700000,
'china': 1409250000,
'usa': 2041280000,
}

gdp = pd.Series(gdp_dict)
print(gdp)

korea     169320000
japan     516700000
china    1409250000
usa      2041280000
dtype: int64


In [105]:
country = pd.DataFrame({
    'population': population,
    'gdp' : gdp
})

In [106]:
country

population         gdp
korea        5180   169320000
japan       12718   516700000
china      141500  1409250000
usa         32676  2041280000

In [108]:
country.index

Index(['korea', 'japan', 'china', 'usa'], dtype='object')

In [110]:
country.columns

Index(['population', 'gdp'], dtype='object')

In [112]:
country['gdp']

korea     169320000
japan     516700000
china    1409250000
usa      2041280000
Name: gdp, dtype: int64

In [113]:
type(country['gdp'])

pandas.core.series.Series

In [120]:
3/6

0.5

In [114]:
country['gdp']/ country['population']

korea    32687.258687
japan    40627.457147
china     9959.363958
usa      62470.314604
dtype: float64

In [115]:
gdp_per_capita = country['gdp']/ country['population']

In [116]:
country

population         gdp
korea        5180   169320000
japan       12718   516700000
china      141500  1409250000
usa         32676  2041280000

In [117]:
country['gdp_per_capita'] = gdp_per_capita

In [118]:
country

population         gdp  gdp_per_capita
korea        5180   169320000    32687.258687
japan       12718   516700000    40627.457147
china      141500  1409250000     9959.363958
usa         32676  2041280000    62470.314604

In [122]:
country.to_csv("./country.csv")
country.to_excel("./country.xlsx")

In [124]:
country = pd.read_csv("./country.csv")

In [125]:
country

Unnamed: 0  population         gdp  gdp_per_capita
0      korea        5180   169320000    32687.258687
1      japan       12718   516700000    40627.457147
2      china      141500  1409250000     9959.363958
3        usa       32676  2041280000    62470.314604

In [127]:
country.population

0      5180
1     12718
2    141500
3     32676
Name: population, dtype: int64

In [128]:
type(country.population)

pandas.core.series.Series

In [129]:
#loc 행과열 , iloc 인덱스: 둘중 어떤걸로 접근할건지.

In [133]:
country.iloc[:]

Unnamed: 0  population         gdp  gdp_per_capita
0      korea        5180   169320000    32687.258687
1      japan       12718   516700000    40627.457147
2      china      141500  1409250000     9959.363958
3        usa       32676  2041280000    62470.314604

In [137]:
country.iloc[:1, :2]
#행 열 로 슬라이싱 해올수 있음

Unnamed: 0  population
0      korea        5180

In [135]:
country.loc[:]

Unnamed: 0  population         gdp  gdp_per_capita
0      korea        5180   169320000    32687.258687
1      japan       12718   516700000    40627.457147
2      china      141500  1409250000     9959.363958
3        usa       32676  2041280000    62470.314604

In [138]:
dataframe = pd.DataFrame(columns=['이름', '나이', '주소'])
dataframe

Empty DataFrame
Columns: [이름, 나이, 주소]
Index: []

In [140]:
dataframe.loc[0]=['이원석','29','서울'] #리스트 형태로 series값 넣어줌
dataframe

이름  나이  주소
0  이원석  29  서울

In [150]:
dataframe.loc[3] = {'이름':'일론머스크', '나이':'40', '주소':'지구'} # 딕셔너리 형태로 해당 값 넣어줌
dataframe


이름   나이   주소  전화번호
0    이원석   29   서울   NaN
1    김태리   30   지구   NaN
2    김태리  NaN  NaN   NaN
3  일론머스크   40   지구   NaN

In [146]:
dataframe['전화번호'] = np.nan # not a number
dataframe

이름   나이   주소  전화번호
0  이원석   29   서울   NaN
1  김태리   30   지구   NaN
2  김태리  NaN  NaN   NaN

In [151]:
dataframe[["이름", "주소"]]

이름   주소
0    이원석   서울
1    김태리   지구
2    김태리  NaN
3  일론머스크   지구

In [152]:
dataframe.dropna()

Empty DataFrame
Columns: [이름, 나이, 주소, 전화번호]
Index: []

In [155]:
dataframe.전화번호 = dataframe.전화번호.fillna('전화번호 없음')

In [156]:
dataframe.전화번호

0    전화번호 없음
1    전화번호 없음
2    전화번호 없음
3    전화번호 없음
Name: 전화번호, dtype: object

In [157]:
dataframe

이름   나이   주소     전화번호
0    이원석   29   서울  전화번호 없음
1    김태리   30   지구  전화번호 없음
2    김태리  NaN  NaN  전화번호 없음
3  일론머스크   40   지구  전화번호 없음

In [159]:
#not a number nan 값이 있는걸 다 날려버림 dropna()
dataframe.dropna()

이름  나이  주소     전화번호
0    이원석  29  서울  전화번호 없음
1    김태리  30  지구  전화번호 없음
3  일론머스크  40  지구  전화번호 없음

In [ ]:
#.astype(int) 이런식으록 값을바꿈


In [160]:
A = pd.DataFrame(np.random.randint(0, 10, (2,2)),columns=list("AB"))
B = pd.DataFrame(np.random.randint(0, 10, (3,3)),columns=list("BAC"))
print(A)
print(B)
A+B
A.add(B, fill_value=0)

   A  B
0  8  4
1  0  5
   B  A  C
0  2  3  4
1  5  9  7
2  4  6  4


A     B    C
0  11.0   6.0  4.0
1   9.0  10.0  7.0
2   6.0   4.0  4.0