In [2]:
import numpy as np

In [3]:
nd1 = np.array([1,2,3,4])
print(nd1)

[1 2 3 4]


In [11]:
print(nd1.ndim)

1


In [5]:
nd2 = np.array([[1,2,3],[4,5,6]])
print(nd2)

[[1 2 3]
 [4 5 6]]


In [12]:
print(nd2.ndim) #number of demention

2


In [6]:
print(type(nd1))

<class 'numpy.ndarray'>


In [8]:
print(type(nd2))

<class 'numpy.ndarray'>


In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a = np.ones((3,4))

In [17]:
a.size

12

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.arange(12).reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])